stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/tuberculosis_xray_dataset.csv
    - src/preprocess.py
    outs:
    - data/processed/data_v1.csv
    - data/processed/data_v2.csv
    - data/processed/data_v3.csv
    - data/processed/data_v4.csv
    - data/processed/data_v5.csv
    - data/processed/data_v6.csv
    - models/le_target.pkl
  train:
    cmd: python src/train.py
    deps:
    - data/processed/data_v1.csv
    - data/processed/data_v2.csv
    - data/processed/data_v3.csv
    - data/processed/data_v4.csv
    - data/processed/data_v5.csv
    - data/processed/data_v6.csv
    - src/train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/data_v1.csv
    - data/processed/data_v2.csv
    - data/processed/data_v3.csv
    - data/processed/data_v4.csv
    - data/processed/data_v5.csv
    - data/processed/data_v6.csv
    - models/model.pkl
    - src/evaluate.py
