preprocess:
  input: data/raw/tuberculosis_xray_dataset.csv
  output: data/processed/data.csv

train:
  input: data/processed/data.csv
  output: data/model/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 10
