preprocess:
  input: data/raw/tuberculosis_xray_dataset.csv
  output:
    - models/le_target.pkl
    - data/processed/data_v1.csv
    - data/processed/data_v2.csv
    - data/processed/data_v3.csv
    - data/processed/data_v4.csv
    - data/processed/data_v5.csv
    - data/processed/data_v6.csv

train:
  input:
    - name: "Label Encoding"
      path: "data/processed/data_v1.csv"
    - name: "One-hot Encoding"
      path: "data/processed/data_v2.csv"
    - name: "Label Encoding + MinMax Scaler"
      path: "data/processed/data_v3.csv"
    - name: "Label Encoding + Standard Scaler"
      path: "data/processed/data_v4.csv"
    - name: "One-hot Encoding + MinMax Scaler"
      path: "data/processed/data_v5.csv"
    - name: "One-hot Encoding + Standard Scaler"
      path: "data/processed/data_v6.csv"
  output: models/model.pkl
