preprocess:
  input: data/raw/tuberculosis_xray_dataset.csv
  output:
    - models/le_target.pkl
    - data/processed/data_v1.csv
    - data/processed/data_v2.csv
    - data/processed/data_v3.csv
    - data/processed/data_v4.csv
    - data/processed/data_v5.csv
    - data/processed/data_v6.csv

train:
  input:
    - data/processed/data_v1.csv
    - data/processed/data_v2.csv
    - data/processed/data_v3.csv
    - data/processed/data_v4.csv
    - data/processed/data_v5.csv
    - data/processed/data_v6.csv
  output: data/model/model.pkl
